site_name: My Docs
plugins:
  - blog:
      #blog_dir: .  
      #authors: true
  - rss:
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
      enabled: !ENV [CI, false]
      date_from_meta:
        as_creation: date
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags