site_name: JASC Space
site_url: https://jangel24.github.io/
nav:
  - Home: 'index.md'
  - Blog: # The blog plugin will handle this section
      - 'blog/index.md'
      - 'blog/posts/hello.md'
    
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.integrate
plugins:
  - blog:
      blog_dir: blog/ # This tells the plugin where your blog root is
      blog_post_dir: blog/posts/ # This tells the plugin where your posts are
      authors: true
  - rss:
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
      enabled: !ENV [CI, false]
      date_from_meta:
        as_creation: date
      match_path: blog/posts/.* date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags