site_name: JASC Space
site_url: https://jangel24.github.io/
nav:
  - Home: index.md # A more conventional way to set your homepage
  - Blog:
    - blog/index.md
theme:
  
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.integrate
plugins:
  - blog:
      #blog_dir: blog/ # Indica que los archivos del blog están en esta carpeta
      #blog_post_dir: blog/posts/ # Indica que las publicaciones están en esta subcarpeta
      blog_dir: .
      authors: true
  - rss:
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
      enabled: !ENV [CI, false]
      date_from_meta:
        as_creation: date
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags