site_name: https://jangel24.github.io/cybersite/
nav:
  - Section:
    - section/index.md 
    - Page 1: posts/hello.md
theme:
  site_url: https://jangel24.github.io/cybersite/
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
plugins:
  - blog:
      blog_dir: .  
      authors: true
  - rss:
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
      enabled: !ENV [CI, false]
      date_from_meta:
        as_creation: date
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags